language: ruby
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake nimbleshop:setup:test_app"
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres

notifications:
  email:
    - neeraj@bigbinary.com
branches:
  only:
    - master
    - test
rvm:
  - 1.9.2
  - 1.9.3
