# Usage
#
# Settings.s3.bucket_name
#
common:
  airbrake_api_key: <%= ENV['AIRBRAKE_API_KEY'] %>
  google_analytics_tracking_id: <%= ENV['GOOGLE_ANALYTICS_TRACKING_ID'] %>

  # this is used for IPN notification and other places where extenal serivce cannot ping localhost
  use_localhost2public_url: true
  default_localhost2public_url: 4a5w.localtunnel.com

  authorizedotnet:
    login_id: <%= ENV['AUTHORIZE_NET_LOGIN_ID'] || '26Daqx7Jtw7R' %>
    transaction_key: <%= ENV['AUTHORIZE_NET_TRANSACTION_KEY'] || '66JWf57KKc82W9y6' %>

  s3:
    access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>

  sendgrid:
    username: <%= ENV['SENDGRID_USERNAME'] %>
    password: <%= ENV['SENDGRID_PASSWORD'] %>
    domain:   <%= ENV['SENDGRID_DOMAIN'] %>

  mailtrapio:
    username: <%= ENV['MAILTRAPIO_USERNAME'] || 'nimbleshop' %>
    password: <%= ENV['MAILTRAPIO_PASSWORD'] || '7663e1f272637a4b' %>

development:
  use_s3: false
  s3:
    bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
  bare_url_with_port: localhost:3000
  using_heroku: false

test:
  use_s3: false
  s3:
    bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
  bare_url_with_port: localhost:3000
  using_heroku: false
  cookie_domain: nimbleshop.net
  use_localhost2public_url: false
  authorize_net:
    login_id: 56yBAar72
    transaction_key: 9r3pbH5bnKH29f7d

staging:
  use_s3: true
  s3:
    bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
  bare_url_with_port: nimbleshop.net
  using_heroku: true
  deliver_email_for_real_in_staging: <%= ENV['DELIVER_EMAIL_FOR_REAL_IN_STAGING'] %>
  cache_images: true

production:
  use_s3: true
  s3:
    bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
  bare_url_with_port: nimbleshop.com
  using_heroku: true
  cache_images: true
  use_localhost2public_url: false
