# Usage
#
# Settings.s3_access_key_id
#
common:
  # TODO move it to shop configuration and add a show link
  s3_access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
  s3_secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>

development:
  using_heroku: false
  # TODO move it to shop configuration and add a show link
  s3_bucket: nibmbleship-development

test:
  using_heroku: false
  cookie_domain: example.com
  s3_bucket: nimbleshop-test

staging:
  # TODO move it to shop configuration
  paypal_return_url: http://nimbleshop-staging.heroku.com/paypal_return
  paypal_notify_url: http://nimbleshop-staging.heroku.com/paypal_payment_notifications

production:
  paypal_return_url: http://nimbleshop.heroku.com/paypal_return
  paypal_notify_url: http://nimbleshop.heroku.com/payment_notifications/paypal
