# Usage
#
# Settings.s3.bucket_name
#
common:
  airbrake_api_key: <%= ENV['AIRBRAKE_API_KEY'] %>

  newrelic_license_key: 2472128dc9484fbc519478eaaa547eea78565e38
  newrelic_app_name: nimbleshop

  s3:
    access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>

  sendgrid:
    username: <%= ENV['SENDGRID_USERNAME'] %>
    password: <%= ENV['SENDGRID_PASSWORD'] %>
    domain:   <%= ENV['SENDGRID_DOMAIN'] %>

  mailtrapio:
    username: <%= ENV['MAILTRAPIO_USERNAME'] %>
    password: <%= ENV['MAILTRAPIO_PASSWORD'] %>

development:
  s3:
    bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
  bare_url_with_port: localhost:3000
  using_heroku: false

test:
  s3:
    bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
  bare_url_with_port: localhost:3000
  using_heroku: false
  cookie_domain: nimbleshop.net

staging:
  s3:
    bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
  bare_url_with_port: nimbleshop.net
  using_heroku: true
  deliver_email_for_real_in_staging: <%= ENV['DELIVER_EMAIL_FOR_REAL_IN_STAGING'] %>

production:
  s3:
    bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
  bare_url_with_port: nimbleshop.com
  using_heroku: true
