# Usage
#
# Settings.s3_access_key_id
#
common:
  s3_access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
  s3_secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
  mail_safe_redirected_email: johnnie.walker@chickscorner.com
  from_email: support@chickscorner.com
  http_basic_authentication_password: <%= ENV['HTTP_BASIC_AUTHENTICATION_PASSWORD']  || 'welcome' %>

development:
  bare_url_with_port: localhost:3000
  using_heroku: false
  # TODO move it to shop configuration and add a show link
  s3_bucket: chickscorner-development

test:
  bare_url_with_port: localhost:3000
  using_heroku: false
  cookie_domain: chickscorner.com
  s3_bucket: chickscorner-test

staging:
  bare_url_with_port: chickscorner-staging.heroku.com
  s3_bucket: chickscorner-staging

production:
  bare_url_with_port: chickscorner.com
  s3_bucket: chickscorner-production
