common: &default
  splitable:
    api_secret: 'AGT568GKLRW39S'
    expires_in: '24'
    submission_url: 'http://lvh.me:3000/split_payments/split?'
    logo_url: 'http://edibleapple.com/wp-content/uploads/2009/04/silver-apple-logo.png'
    api_key: '42398cc9ac420bf4'
    name: 'Splitable'
    description: "
<p>
  Splitable helps split the cost of product with friends and family.
</p>

<p>
  <a href='http://splitable.com'>
   more information
  </a>
</p>
"
  authorize_net:
    login_id: '56yBAar72'
    transaction_key: '9r3pbH5bnKH29f7d'
    company_name_on_creditcard_statement: 'chickscorner LLC'
    name: 'Authorize.net'
    description: "
<p>
  Authorize.Net is a payment gateway service provider allowing merchants
  to accept credit card and electronic checks paymentsn. Authorize.Net
  claims a user base of over 305,000 merchants, which would make them
  the Internet's largest payment gateway service provider.
</p>

<p>
  It also provides an instant test account which you can use while
  your application is being processed.
</p>
"
  paypal_website_payments_standard:
    name: 'Paypal website payments standard'
    merchant_email_address: 'seller_1323037155_biz@bigbinary.com'
    return_url: 'http://localhost:3000/paypal_return'
    notify_url: 'http://localhost:3000/payment_notifications/paypal'
    request_submission_url: 'https://www.sandbox.paypal.com/cgi-bin/webscr?'
    description: "
<p>
  Paypal website payments standard is a payment solution provided by
  paypal which allows merchant to accept credit card and paypal payments.
  There is no monthly fee and no setup fee by paypal for this account.
</p>

<p>
  <a href='https://merchant.paypal.com/cgi-bin/marketingweb?cmd=_render-content&content_ID=merchant/wp_standard&nav=2.1.0'>
   more information
  </a>
</p>
"
development:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
test:
  <<: *default
