common:
  splitable:
    api_secret: 92746e4d66cb8993
    expires_in: 24
    api_key: 92746e4d66cb8993
    name: Splitable
    permalink: splitable
    description: <p> Splitable helps split the cost of product with friends and family.  </p> <p> <a href="http://splitable.com"> more information </a> </p>

  paypalwp:
    name: Paypal website payments standard
    permalink: paypalwp
    paymentaction: authorize
    merchant_email: seller_1323037155_biz@bigbinary.com
    description: <p> Paypal website payments standard is a payment solution provided by paypal which allows merchant to accept credit card and paypal payments.  There is no monthly fee and no setup fee by paypal for this account.  </p> <p> <a href='https://merchant.paypal.com/cgi-bin/marketingweb?cmd=_render-content&content_ID=merchant/wp_standard&nav=2.1.0'> more information </a> </p>

development:
staging:
production:
test:
